# Generated by Django 2.2.26 on 2022-06-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_default23'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Default23',
        ),
    ]
